### ISSUE TITLE
Feststellung von Fehlern

### ISSUE THREAD

**Issue by Mr-Robotiko** [GSO-SW/gitstarted_zusammenfassung-gsodev#3]
- Git Commit ist falsch erläutert wurden. Nicht alle Dateien gehen in die Staging Area, sondern geaddete Dateien in der Staging Area werden in den Repository commitet.
- "Ein zweite Weg ...", ".. sind (V)erweise ..."
- "_" am Satzanfang sind zu bemängeln. 
- "in den (n)ormalen Bereiche .. ".

**Comment by MustafaSataric** [comment]
Opfer^2
