### ISSUE TITLE
Bewertung von Philip D.

### ISSUE THREAD

**Issue by GanzundgarnichtPhilip** [GSO-SW/gitstarted_zusammenfassung-gsodev#8]
Einfach Genial🤯

Hier noch ein Erklärungsvideo für einen Fehler der begangen wurde: [https://youtu.be/dQw4w9WgXcQ](url)

**Comment by Mani-Big-Badam** [comment]
sehr hilfreiches Erklärungsvideo 10/10 punkten 😏

**Comment by mohamed26n** [comment]
Danke !
